version: '3'
services:
  nginx:
    build:
      context: ./nginx
      dockerfile: ./Dockerfile
    environment:
        NGINX_ENVSUBST_TEMPLATE_SUFFIX: ".conf"
        USER_FUNCTION_HOST: cloudstate:9000
    ports:
      - 80:80
      - 90:90
      - 443:443
  ui: 
    build:
      context: ./ui
      dockerfile: ./Dockerfile
    environment: 
      REACT_APP_SERVICE_HOST: "http://localhost"
    ports:
      - 3001:3001    
  service: 
    build:
      context: ./service
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080   
  cloudstate: 
    image: cloudstateio/cloudstate-proxy-dev-mode:latest
    container_name: cloudstate
    environment:
      - USER_FUNCTION_HOST=service
    ports:
      - 9000:9000
    links:
      - service
